name: Release docker image
on:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      QT_VERSION: 6.5.3
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo REPO_SLUG="${repo,,}" >> ${GITHUB_ENV}
        env: 
          repo: ${{ github.repository}}
      
      - run: echo IMAGE_URI="ghcr.io/${{ env.REPO_SLUG }}" >> ${GITHUB_ENV}
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # should push after next step success
          build-args: |
            QT_VERSION=${{ env.QT_VERSION }}
          tags: |
            ${{ env.IMAGE_URI }}:latest
            ${{ env.IMAGE_URI }}:${{ env.QT_VERSION }}
            ${{ env.IMAGE_URI }}:${{ env.QT_VERSION }}-base-tools

      - uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.IMAGE_URI }}:6.5.3-base-tools
          run: |
            git clone https://github.com/euler0/mini-cmake-qt.git
            git reset --hard 39d568a05318bec619f470942a18980968df22c3
            cd mini-cmake-qt
            cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
            cmake --build build

      - run: |
          docker push ${{ env.IMAGE_URI }}:latest
          docker push ${{ env.IMAGE_URI }}:${{ env.QT_VERSION }}
          docker push ${{ env.IMAGE_URI }}:${{ env.QT_VERSION }}-base-tools
